Removed redundand _run_cmd
duckietown/duckietown-shell-commands pull request #429
Opened 2023-11-17 11:12 UTC by Tuxliri

2023-11-19 05:54 UTC, afdaniele requested changes

2023-11-19 05:54 UTC, afdaniele commented on devel/build/command.py
> +            for shell_command in project.hooks.hooks['pre-build']:
according to https://github.com/duckietown/lib-dtproject/pull/5, the object `shell_command` is of type `Hook`, so we need three things. Rename `shell_command` -> `hook`.

Use it as
```
_run_cmd(hook.command)
```

Use the value of `hook.required` somehow here.

2023-11-21 11:23 UTC, Tuxliri commented on vscode/open/command.py
> -                    raise e
There are several of these `_run_cmd` functions scattered throughout various commands, we should unify them.

2023-11-21 11:26 UTC, Tuxliri commented on utils/dtproject_utils.py
> +        dtslogger.warning(f"Project format version {project.format.version} does not support hooks. Skipping...")
Added the following behavior:

- If a `hook` is `required` and fails, the command stops.
- If a `hook` is NOT `required` and fails there is a warning printed.

2023-11-21 11:26 UTC, merged