Dtsw 5312 investigate format discrepancy of extrinsic calibration for backported daffy
duckietown/duckietown-shell-commands pull request #449
Opened 2024-03-15 17:16 UTC by Tuxliri

2024-03-25 15:19 UTC, afdaniele requested changes

2024-03-25 15:19 UTC, afdaniele commented on duckiebot/calibrate_extrinsics/command.py
> +        prog = "dts duckiebot calibrate_extrisics DUCKIEBOT_NAME"
typo

2024-03-25 15:19 UTC, afdaniele commented on duckiebot/calibrate_extrinsics/command.py
> +        parser.add_argument("hostname", default=None, help="Name of the Duckiebot to calibrate")
should be `duckiebot`

2024-03-25 15:19 UTC, afdaniele commented on duckiebot/calibrate_extrinsics/command.py
> +            "opmanual-duckiebot/operations/calibration_camera/index.html#extrinsic-camera-calibration.\n "
let's make sure the docs are updated

2024-04-02 10:32 UTC, Tuxliri commented on duckiebot/calibrate_extrinsics/command.py
> +            "opmanual-duckiebot/operations/calibration_camera/index.html#extrinsic-camera-calibration.\n "
This has been completed.

2024-04-09 14:04 UTC, merged